#!/usr/bin/env bash

# Get all active IPv4 addresses using ip command
ip_addresses=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Display the active IPv4 addresses
echo "$ip_addresses"

